// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0NNIKxiW7hxBECP97JtHYMnYdxy2mSbs',
    appId: '1:483808996809:web:ea5876c271357dae9a0c18',
    messagingSenderId: '483808996809',
    projectId: 'my-flutter-backend-2',
    authDomain: 'my-flutter-backend-2.firebaseapp.com',
    storageBucket: 'my-flutter-backend-2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0b22G8WLjD2TFFiABX9QMgOiLxfiNeKs',
    appId: '1:483808996809:android:54f7cf846e225afc9a0c18',
    messagingSenderId: '483808996809',
    projectId: 'my-flutter-backend-2',
    storageBucket: 'my-flutter-backend-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOlVCppht5ymfBPSCDNxhjQ8lFukuYjfA',
    appId: '1:483808996809:ios:d81607cb7652555f9a0c18',
    messagingSenderId: '483808996809',
    projectId: 'my-flutter-backend-2',
    storageBucket: 'my-flutter-backend-2.firebasestorage.app',
    iosBundleId: 'com.example.myBackendApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOlVCppht5ymfBPSCDNxhjQ8lFukuYjfA',
    appId: '1:483808996809:ios:d81607cb7652555f9a0c18',
    messagingSenderId: '483808996809',
    projectId: 'my-flutter-backend-2',
    storageBucket: 'my-flutter-backend-2.firebasestorage.app',
    iosBundleId: 'com.example.myBackendApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0NNIKxiW7hxBECP97JtHYMnYdxy2mSbs',
    appId: '1:483808996809:web:79abacbaf8b1386b9a0c18',
    messagingSenderId: '483808996809',
    projectId: 'my-flutter-backend-2',
    authDomain: 'my-flutter-backend-2.firebaseapp.com',
    storageBucket: 'my-flutter-backend-2.firebasestorage.app',
  );
}
